### ISSUE TITLE
Intermittent error in fresh installation due to missing data directories

### ISSUE THREAD

**Issue by sk364** [l0k3ndr/tull#1]
Steps to reproduce:

* Install tull
* Run command `tull` (args don't matter)
* `FileNotFound` error is raised
```
Traceback (most recent call last):
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f40299ba6a0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=17171): Max retries exceeded with url: /tull/api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40299ba6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sh/random/tull/./tull", line 168, in ensure_tull_server
    requests.get(TULL_API_URL)
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/sh/random/tull/venv/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=17171): Max retries exceeded with url: /tull/api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40299ba6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sh/random/tull/./tull", line 321, in <module>
    ensure_tull_server()
  File "/home/sh/random/tull/./tull", line 170, in ensure_tull_server
    f = open(TULL_META_DIR + "tull-server.log", "a+")
FileNotFoundError: [Errno 2] No such file or directory: '/home/sh/.tull/meta/tull-server.log'
```

**Comment by l0k3ndr** [comment]
merged the fix to master. will release it in next tag.
